// lib/auth/session.ts
//
// The ONE auth resolver (architecture §0.1, ownership-map). Resolves:
//   Supabase user (auth.uid) → employees row → employee_roles
// into a single `AuthUser`. No `getAuthContext`/`getCurrentEmployee` duplicates exist.
//
// Keyless / DEMO contract: if Supabase is NOT configured, or DEMO_MODE is on and there
// is no real session, we return a synthetic in-memory demo AuthUser and DO NOT touch
// the DB — so every view renders keyless. Once real keys + a session exist, the real
// employee/roles are resolved with RLS.

import { isConfigured } from '@/lib/config/env';
import { isDemoMode } from '@/lib/config/flags';
import { appTable, createClient } from '@/lib/supabase/server';
import type { AppRole, AuthUser } from '@/lib/types';

/** The synthetic demo identity used for keyless boot (no DB, no session). */
const DEMO_USER: AuthUser = {
  userId: 'demo-user',
  employeeId: 'demo-employee',
  functionId: 'demo-function',
  displayName: 'Demo User',
  email: null,
  // In the single-user demo the user holds every role so all chrome is reachable.
  roles: ['developer', 'manager', 'function_lead', 'admin'],
  isDemo: true,
};

/** Return a copy of the demo user (so callers can't mutate the shared object). */
export function demoUser(): AuthUser {
  return { ...DEMO_USER, roles: [...DEMO_USER.roles] };
}

/**
 * Resolve the current AuthUser, or null when unauthenticated (and not in a demo
 * fallback). Never throws on a missing key — returns the demo user instead so views
 * render keyless.
 */
export async function getAuthUser(): Promise<AuthUser | null> {
  // Keyless boot: no Supabase → demo context (if DEMO_MODE) else unauthenticated.
  if (!isConfigured('supabase')) {
    return isDemoMode() ? demoUser() : null;
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    // No live session. In DEMO_MODE, fall back to the demo identity so the dev loop
    // isn't a magic-link wall; otherwise unauthenticated.
    return isDemoMode() ? demoUser() : null;
  }

  return getEmployeeForUid(user.id, user.email ?? null);
}

/**
 * Resolve a Supabase auth uid → its employee row + roles. Returns null if no
 * employee is linked yet (e.g. a fresh sign-in before provisioning). Demo fallback
 * applies when DEMO_MODE is on and the lookup yields nothing.
 */
export async function getEmployeeForUid(uid: string, email: string | null): Promise<AuthUser | null> {
  if (!isConfigured('supabase')) {
    return isDemoMode() ? demoUser() : null;
  }

  const supabase = await createClient();

  // The generated `Database` placeholder has no Tables yet (regenerated by
  // `npm run db:types`). Until then, query app tables through `appTable()`, a
  // loosely-typed escape hatch, so this resolver type-checks keyless. Once types are
  // generated the queries can be tightened to the typed client.
  const db = appTable(supabase);

  // employees is keyed to auth.users via user_id. RLS lets a user read their own row.
  const { data: employee } = await db
    .from('employees')
    .select('id, function_id, display_name, email, is_demo')
    .eq('user_id', uid)
    .maybeSingle();

  if (!employee) {
    return isDemoMode() ? demoUser() : null;
  }

  const emp = employee as {
    id: string;
    function_id: string;
    display_name: string;
    email: string | null;
    is_demo: boolean;
  };

  const { data: roleRows } = await db.from('employee_roles').select('role').eq('employee_id', emp.id);

  const roles = (((roleRows ?? []) as { role: AppRole }[]) || []).map((r) => r.role);

  return {
    userId: uid,
    employeeId: emp.id,
    functionId: emp.function_id,
    displayName: emp.display_name,
    email: emp.email ?? email,
    roles: roles.length > 0 ? roles : ['developer'],
    isDemo: emp.is_demo,
  };
}

/** Like getAuthUser but throws when unauthenticated — for paths that require a user. */
export async function requireAuthUser(): Promise<AuthUser> {
  const user = await getAuthUser();
  if (!user) {
    throw new Error('Unauthorized: no authenticated user.');
  }
  return user;
}
